# Generated by Django 4.1.7 on 2023-02-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "car_brand",
                    models.CharField(max_length=30, verbose_name="Car brand"),
                ),
                (
                    "car_model",
                    models.CharField(max_length=50, verbose_name="Car model"),
                ),
                ("release_year", models.IntegerField(verbose_name="Release year")),
                ("car_type", models.CharField(max_length=9, verbose_name="Car type")),
                ("fuel_type", models.CharField(max_length=8, verbose_name="Fuel type")),
                (
                    "gearbox_type",
                    models.CharField(max_length=9, verbose_name="Gearbox type"),
                ),
                (
                    "drivetrain_type",
                    models.CharField(max_length=4, verbose_name="Drivetrain type"),
                ),
                (
                    "engine_type",
                    models.CharField(max_length=4, verbose_name="Engine type"),
                ),
                (
                    "engine_volume",
                    models.DecimalField(
                        decimal_places=1, max_digits=3, verbose_name="Engine volume"
                    ),
                ),
                ("hp", models.IntegerField(verbose_name="Engine horse powers")),
                ("torque", models.IntegerField(verbose_name="Engine torque")),
                ("seat_places", models.IntegerField(verbose_name="Seat places")),
                ("is_active", models.BooleanField(verbose_name="Is active")),
            ],
        ),
    ]
