# Generated by Django 4.1.7 on 2023-02-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_type",
            field=models.CharField(
                choices=[
                    ("suv", "SUV"),
                    ("sedan", "Sedan 4-d"),
                    ("coupe", "Coupe 2-d"),
                    ("sport", "Sportcar"),
                    ("hyper", "Hypercar"),
                    ("minivan", "Mini-van"),
                    ("van", "Van"),
                    ("truck", "Truck"),
                    ("wagon", "Wagon"),
                    ("muscle", "Musclecar"),
                    ("etc", "Etc."),
                ],
                max_length=7,
                verbose_name="Car type",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="drivetrain_type",
            field=models.CharField(
                choices=[
                    ("awd", "AWD"),
                    ("fwd", "FWD"),
                    ("rwd", "RWD"),
                    ("4wd", "4WD"),
                    ("etc", "Etc."),
                ],
                max_length=3,
                verbose_name="Drivetrain type",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="engine_type",
            field=models.CharField(
                choices=[
                    ("i3", "I3"),
                    ("i4", "I4"),
                    ("i5", "I5"),
                    ("i6", "I6"),
                    ("v6", "V6"),
                    ("v8", "V8"),
                    ("v10", "V10"),
                    ("v12", "V12"),
                    ("w10", "W10"),
                    ("w12", "W12"),
                    ("e", "E"),
                    ("etc", "Etc."),
                ],
                max_length=3,
                verbose_name="Engine type",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="fuel_type",
            field=models.CharField(
                choices=[
                    ("gas", "Gasoline"),
                    ("diesel", "Diesel"),
                    ("hybrid", "Hybrid"),
                    ("electro", "Electro"),
                    ("etc", "Etc."),
                ],
                max_length=7,
                verbose_name="Fuel type",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="gearbox_type",
            field=models.CharField(
                choices=[
                    ("m", "Manual"),
                    ("a", "Automatic"),
                    ("r", "Robotic"),
                    ("v", "Variable"),
                    ("s", "Sequental"),
                    ("e", "Etc."),
                ],
                max_length=1,
                verbose_name="Gearbox type",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="hp",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Engine horse powers"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="seat_places",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Seat places"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="torque",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Engine torque"
            ),
        ),
    ]
