# Generated by Django 4.1.7 on 2023-02-27 11:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("car", "0003_engine_remove_car_engine_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="drivetrain_type",
        ),
        migrations.RemoveField(
            model_name="car",
            name="gearbox_type",
        ),
        migrations.RemoveField(
            model_name="car",
            name="seat_places",
        ),
        migrations.RemoveField(
            model_name="engine",
            name="engine_type",
        ),
        migrations.RemoveField(
            model_name="engine",
            name="torque",
        ),
    ]
