# Generated by Django 4.1.7 on 2023-03-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Naming")),
                (
                    "foundation_year",
                    models.IntegerField(verbose_name="Year of foundation"),
                ),
                ("is_active", models.BooleanField(verbose_name="Is active")),
            ],
        ),
    ]
