# Generated by Django 4.1.7 on 2023-03-15 09:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("car", "0001_initial"),
        ("provider", "0002_carsinproviderstock"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderDiscounts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_dates",
                    models.DurationField(verbose_name="Dates of promotion"),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Promotion naming"),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=1000, verbose_name="Promotion description"
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="car.car",
                        verbose_name="Car",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="provider.provider",
                        verbose_name="Provider",
                    ),
                ),
            ],
        ),
    ]
