# Generated by Django 4.1.7 on 2023-03-20 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("provider", "0003_providerdiscounts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="providerdiscounts",
            name="discount",
        ),
        migrations.AddField(
            model_name="providerdiscounts",
            name="price_during_discount",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=8,
                verbose_name="Car price during discount",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="providerdiscounts",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="provider.carsinproviderstock",
                verbose_name="Car in stock",
            ),
        ),
    ]
