# Generated by Django 4.1.7 on 2023-03-20 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("provider", "0004_remove_providerdiscounts_discount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="providerdiscounts",
            name="discount_dates",
        ),
        migrations.AddField(
            model_name="providerdiscounts",
            name="discount_date_from",
            field=models.DateField(
                default=datetime.date(2000, 11, 11),
                verbose_name="Date of promotion start",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="providerdiscounts",
            name="discount_date_to",
            field=models.DateField(
                default=datetime.date(2001, 9, 9),
                verbose_name="Date of promotion ending",
            ),
            preserve_default=False,
        ),
    ]
