# Generated by Django 4.1.7 on 2023-03-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Buyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Full name"),
                ),
                ("age", models.IntegerField(verbose_name="Age")),
                (
                    "gender",
                    models.CharField(
                        choices=[("men", "Men"), ("women", "Women")],
                        max_length=5,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Buyer's balance"
                    ),
                ),
                ("is_active", models.BooleanField(verbose_name="Is active")),
            ],
        ),
    ]
