# Generated by Django 4.1.7 on 2023-03-03 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("car", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Full name"),
                ),
                ("age", models.IntegerField(verbose_name="Age")),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        max_length=6,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Buyer's balance"
                    ),
                ),
                ("is_active", models.BooleanField(verbose_name="Is active")),
            ],
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Maximum cost"
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Quantity of cars")),
                ("is_active", models.BooleanField(verbose_name="Is active")),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buyer.buyer",
                        verbose_name="Buyer",
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="car.car",
                        verbose_name="Car",
                    ),
                ),
            ],
        ),
    ]
