# Generated by Django 4.1.7 on 2023-03-14 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("buyer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer",
            name="account",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="buyer",
            name="age",
            field=models.IntegerField(default=0, verbose_name="Age"),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="balance",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                verbose_name="Buyer's balance",
            ),
        ),
        migrations.AlterField(
            model_name="buyer",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is active"),
        ),
    ]
