# Generated by Django 4.1.7 on 2023-03-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buyer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                max_length=6,
                verbose_name="Gender",
            ),
        ),
    ]
