# Generated by Django 4.1.7 on 2023-03-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buyer", "0002_buyer_account_alter_buyer_age_alter_buyer_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyer",
            name="age",
            field=models.IntegerField(verbose_name="Age"),
        ),
    ]
