# Generated by Django 4.1.7 on 2023-03-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car", "0001_initial"),
        ("dealership", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardealership",
            name="preferred_car_release_year_from",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Release year from"
            ),
        ),
        migrations.AddField(
            model_name="cardealership",
            name="preferred_car_release_year_to",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Release year to"
            ),
        ),
        migrations.AddField(
            model_name="cardealership",
            name="preferred_car_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("suv", "SUV"),
                    ("sedan", "Sedan 4-d"),
                    ("coupe", "Coupe 2-d"),
                    ("sport", "Sportcar"),
                    ("hyper", "Hypercar"),
                    ("minivan", "Mini-van"),
                    ("van", "Van"),
                    ("truck", "Truck"),
                    ("wagon", "Wagon"),
                    ("muscle", "Musclecar"),
                    ("etc", "Etc."),
                ],
                max_length=20,
                null=True,
                verbose_name="Car type",
            ),
        ),
        migrations.AddField(
            model_name="cardealership",
            name="preferred_fuel_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gas", "Gasoline"),
                    ("diesel", "Diesel"),
                    ("hybrid", "Hybrid"),
                    ("electro", "Electro"),
                    ("etc", "Etc."),
                ],
                max_length=20,
                null=True,
                verbose_name="Fuel type",
            ),
        ),
        migrations.AlterField(
            model_name="cardealership",
            name="preferred_cars_list",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="car.car",
                verbose_name="List of preferred cars",
            ),
        ),
    ]
