# Generated by Django 4.1.7 on 2023-03-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("car", "0001_initial"),
        ("dealership", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cardealership",
            name="preferred_cars_list",
            field=models.ManyToManyField(to="car.car"),
        ),
    ]
