# Generated by Django 4.2 on 2023-04-17 15:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("buyer", "0005_remove_offer_quantity_alter_offer_max_cost"),
        ("car", "0002_remove_car_is_active_remove_engine_is_active"),
        ("dealership", "0003_carsindealershipstock"),
    ]

    operations = [
        migrations.CreateModel(
            name="DealershipPersonalDiscounts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actual_discount",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Actual discount",
                    ),
                ),
                (
                    "quantity_of_bought_cars",
                    models.IntegerField(verbose_name="Quantity of bought cars"),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buyer.buyer",
                        verbose_name="Buyer",
                    ),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dealership.cardealership",
                        verbose_name="Dealership",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DealershipDiscounts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_date_from",
                    models.DateField(verbose_name="Date of promotion start"),
                ),
                (
                    "discount_date_to",
                    models.DateField(verbose_name="Date of promotion ending"),
                ),
                (
                    "price_during_discount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="Car price during discount",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Promotion naming"),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=1000, verbose_name="Promotion description"
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="car.car",
                        verbose_name="Car in stock",
                    ),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dealership.cardealership",
                        verbose_name="Dealership",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DealerSales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Total price"
                    ),
                ),
                (
                    "sell_date",
                    models.DateTimeField(auto_now=True, verbose_name="Date of sale"),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="buyer.buyer",
                        verbose_name="Buyer",
                    ),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="car.car",
                        verbose_name="Car",
                    ),
                ),
                (
                    "dealer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dealership.cardealership",
                        verbose_name="Dealership",
                    ),
                ),
            ],
        ),
    ]
